apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels: 
    app   : my-web-deployment
    env   : prod
    tier  : frontend
    owner : NikitaTertyschny
spec:
  selector:
    matchLabels:
      project: mypods
  template:
    metadata:
      labels:
        roject: mypods
    spec:
      containers:
      - name: mypods-nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
