apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling-service
  labels: 
    app   : my-web-deployment
    env   : prod
    tier  : frontend
    owner : NikitaTertyschny
spec:
  selector:
    matchLabels:
      project: autoservice
  template:
    metadata:
      labels:
        project: autoservice #  Service will look for those PODS labels!
    spec:
      containers:
      - name: mypods-nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: mypods-tomcat
        image: tomcat:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
--- 
apiVersion : autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myautoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mmy-web-deployment-autoscaling-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels: 
    env: prod
    owner: NikitaTertyschny
spec:
  selector:
    project:  autoservice # Selecting PODS with those Labels
  ports:
    - name       : my-web-app-listener
      protocol   : TCP
      port       : 80  # Port on Load Balancer
      targetPort : 80  # Port on POD
    - name       : not-my-web-app-listener
      protocol   : TCP
      port       : 8888  # Port on Load Balancer
      targetPort : 8080  # Port on POD
  type: ClusterIP